name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
#    - name: configure
#      run: ./configure
    - name: make
      run: make all DEBUG=1
      working-directory: ./src/raspberrypi
#    - name: make check
#      run: make check
#    - name: make distcheck
#      run: make distcheck

  buildroot-image:
    runs-on: ubuntu-latest
    steps:
      - name: git-fetch buildroot
        run: git clone git://git.busybox.net/buildroot
#      - uses: actions/checkout@v2
#        with: 
#          repository: 'git://git.busybox.net/buildroot'
      - name: make defconfig
        run: make raspberrypi4_defconfig
        working-directory: ./buildroot
      - name: make
        run: make all
        working-directory: ./buildroot
